version: '3.8'

# for deployment

services:
  app:
    build:
      context: .
      dockerfile: TranscEND.Dockerfile
    volumes:
      - /Users/zstenger/Desktop/42/Transcendence:/app/
    ports:
      - 8000:8000
    # restart: unless-stopped
    entrypoint: /app/start.sh