version: '3.7'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: unless-stopped

  backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./src/docker/backend.Dockerfile
  
  frontend:
    depends_on:
      - postgres
      - backend
    build:
      context: .
      dockerfile: ./src/docker/frontend.Dockerfile

  transcendence:
    container_name: transcendence
    depends_on:
      - postgres
      - backend
      - frontend
    build:
      context: .
      dockerfile: 
    env_file:
      - .env
    restart: unless-stopped