version: '3.7'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      DATABASE_NAME: ${DBNAME}
      DATABASE_USER: ${DBUSER}
      DATABASE_USER_PW: ${DBUSERPW}
    env_file:
      - .env
    restart: unless-stopped

  transcendence:
    image: transcendence
    container_name: transcendence
    build:
      context: .
      dockerfile: ./src/docker/transcendence.Dockerfile
    env_file:
      - .env
    restart: unless-stopped