# Generated by Django 5.0 on 2024-02-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
