# Generated by Django 5.0 on 2024-01-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0014_appuser_aboutme_appuser_match_history_appuser_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='intra_level',
            field=models.FloatField(default=0),
        ),
    ]
